version: '3.8'

services:
  db:
    image: postgres:alpine3.16
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hw_28
    restart: always
    ports:
      - '5432:5432'

volumes:
  postgres_database: