# Generated by Django 4.1.3 on 2022-12-11 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(0)]),
            preserve_default=False,
        ),
    ]
