# Generated by Django 4.1.3 on 2022-12-11 14:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[user.validators.CheckBirthDate], verbose_name='День рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Запрещена регистрация с почтового адреса в домене rambler.ru.', regex='@rambler.ru')], verbose_name='E-mail'),
        ),
    ]
